# Generated by Django 5.1.1 on 2024-11-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('customOrderID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('customDescription', models.CharField(max_length=200)),
                ('customPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
