# Generated by Django 5.1.1 on 2024-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_cart_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cart_item_images/'),
        ),
    ]
