# Generated by Django 5.1.1 on 2024-10-02 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
