# Generated by Django 5.1.1 on 2024-10-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_delivery_address',
            field=models.TextField(default='sunny brooke 2'),
            preserve_default=False,
        ),
    ]
