# Generated by Django 5.1.1 on 2024-11-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_order_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
