# Generated by Django 5.1.1 on 2024-11-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_order_custom_order_order_custom_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='media/payment_proofs/'),
        ),
    ]
