# Generated by Django 5.1.1 on 2024-11-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='media/payment_qr/'),
        ),
    ]
