# Generated by Django 5.1.1 on 2024-11-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_order_payment_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='media/payment_qr/')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_qr',
        ),
    ]
